joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0

teleop_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.8 #12.0 #0.8           #0.7
    scale_linear_turbo:
      x: 2.5 #2.0 #15.0 #2.0      #1.0

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 2.0        #1.32
    scale_angular_turbo:
      yaw: 2.5 #6.0 #48.0 #5.0    #1.62


    enable_button: 4
    enable_turbo_button: 5

    require_enable_button: true